name: fannelance_worker
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  iconsax: ^0.0.8
  intl: ^0.19.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0
  flutter_secure_storage: ^9.2.2
  intl_phone_field: ^3.2.0
  pinput: ^4.0.0
  jwt_decoder: ^2.0.1
  dio: ^5.4.0
  flutter_dotenv: ^5.1.0
  flutter_rating_bar: ^4.0.1



dev_dependencies:

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logos/
    - .env

  fonts:
    - family: Gilroy-SemiBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf

    - family: Gilroy-Bold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf

